"""empty message

Revision ID: 47679c8cf94e
Revises: 
Create Date: 2024-03-20 09:42:35.333900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47679c8cf94e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity')
    op.drop_table('project')
    op.drop_table('financialreport')
    op.drop_table('report')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=20), nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.Column('password', sa.VARCHAR(length=60), nullable=False),
    sa.Column('is_admin', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('report',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('activity_id', sa.INTEGER(), nullable=False),
    sa.Column('report_title', sa.VARCHAR(length=200), nullable=True),
    sa.Column('date_from', sa.DATETIME(), nullable=True),
    sa.Column('date_to', sa.DATETIME(), nullable=True),
    sa.Column('number_reached_male', sa.INTEGER(), nullable=True),
    sa.Column('number_reached_female', sa.INTEGER(), nullable=True),
    sa.Column('written_report', sa.VARCHAR(length=200), nullable=True),
    sa.Column('photos', sa.VARCHAR(length=200), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financialreport',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('budget', sa.FLOAT(), nullable=True),
    sa.Column('expenditure', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('donor', sa.VARCHAR(length=100), nullable=True),
    sa.Column('thematic_area', sa.VARCHAR(length=100), nullable=True),
    sa.Column('start_date', sa.DATETIME(), nullable=True),
    sa.Column('end_date', sa.DATETIME(), nullable=True),
    sa.Column('project_amount', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('target_beneficiaries', sa.VARCHAR(length=200), nullable=True),
    sa.Column('target_beneficiaries_male', sa.INTEGER(), nullable=True),
    sa.Column('target_beneficiaries_female', sa.INTEGER(), nullable=True),
    sa.Column('budget_amount', sa.FLOAT(), nullable=True),
    sa.Column('approved_budget_amount', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
