"""empty message

Revision ID: fcda28e3b1cc
Revises: 47679c8cf94e
Create Date: 2024-03-20 11:23:45.756344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcda28e3b1cc'
down_revision = '47679c8cf94e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financialreport', sa.Column('total_expenditure', sa.Float(), nullable=True))
    op.drop_column('financialreport', 'expenditure')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financialreport', sa.Column('expenditure', sa.FLOAT(), nullable=True))
    op.drop_column('financialreport', 'total_expenditure')
    # ### end Alembic commands ###
